# Generated by Django 3.0.6 on 2020-11-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='image',
            new_name='report_image',
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
