# Generated by Django 3.0.6 on 2020-11-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20201121_2305'),
        ('reports', '0005_auto_20201121_2307'),
    ]

    operations = [
    ]
